gpt-3.5-turbo-0613:
    import: "./openai-chat.yaml"
    parameters:
        name: "gpt-3.5-turbo-0613"
        body:
            model: "gpt-3.5-turbo-0613"
            max_tokens: 512

text-davinci-003:
    import: "./openai-text.yaml"
    parameters:
        name: "text-davinci-003"
        body:
            model: "text-davinci-003"
            max_tokens: 512

text-davinci-002:
    import: "./openai-text.yaml"
    parameters:
        name: "text-davinci-002"
        body:
            model: "text-davinci-002"
            max_tokens: 512


ollama-qwen-4b:
  import: "./ollama-qwen-chat.yaml"
  parameters:
    name: "ollama-qwen-4b"
    body:
      model: "qwen3:4b"

ollama-qwen-8b:
  import: "./ollama-qwen-chat.yaml"
  parameters:
    name: "ollama-qwen-8b"
    body:
      model: "qwen3:8b"

ollama-gemma2-2b:
  import: "./ollama-qwen-chat.yaml"
  parameters:
    name: "ollama-gemma2-2b"
    body:
      model: "gemma2:2b"

ollama-gemma2-9b:
  import: "./ollama-qwen-chat.yaml"
  parameters:
    name: "ollama-gemma2-9b"
    body:
      model: "gemma2:9b"