import: definition.yaml

concurrency:
  task:
    dbbench-std: 1
  agent:
    ollama-qwen-4b: 1
    ollama-qwen-8b: 1
    ollama-gemma2-2b: 1
    ollama-gemma2-9b: 1

assignments:
  - agent:
      - ollama-qwen-4b
      - ollama-qwen-8b
      - ollama-gemma2-2b
      - ollama-gemma2-9b
    task:
      - dbbench-std

output: "outputs/{TIMESTAMP}"